export {default as Pages_root} from "./PagesRoot"
export {default as Home} from "./HomePage"
export {default as Gear} from "./Gear"
export {default as Oyahs} from "./Oyahs"
export {default as Surah} from "./Surah"
export {default as Namoz_vaqti} from "./NamozVaqt"
export {default as Error} from "./ErrorPage"